baseURL = "/"
languageCode = "en-us"
title = "Michelle Lim"
theme = "ezhil"

copyright = "Copyright © 2020 Michelle Lim"

# Enable syntax highlighting.
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
googleAnalytics = "UA-177547603-1"

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 3

# Number of characters to show in summary.
summaryLength = 15

[params]
    description = "Hi! I’m Michelle Lim. I’m the Growth Lead at Warp. I also write essays. "
    images = ["https://s3.amazonaws.com/www.michellelim.org/images/self.jpg"]

    # Content types which are included in home page recent posts list.
    mainSections = ["post"]

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page", "post"]

    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true

    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "https://s3.amazonaws.com/www.michellelim.org/icons/favicon.ico"

    # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
    # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
    # you can specify custom css path as `css/custom.css`.
    customCSS = "css/custom.css"

    customJS = ["https://platform.twitter.com/widgets.js"]

    mode = "auto"

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).


[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/michlimlim"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/michlimlim"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/michlimlim"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:limxlmichelle@gmail.com"


# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writing"
url = "/writing"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Investments"
url = "/investments"
weight = 4

[[menu.main]]
name = "Art"
url = "/art"
weight = 5

[[menu.main]]
name = "Subscribe"
url = "/subscribe"
weight = 6

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "personal"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://www.michellelim.org/?region=us-east-1"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "E1LJGS4J5XAC6O"

# Optionally, you can include or exclude specific files.
# See https://godoc.org/github.com/gobwas/glob#Glob for the glob pattern syntax.
# If non-empty, the pattern is matched against the local path.
# All paths are matched against in their filepath.ToSlash form.
# If exclude is non-empty, and a local or remote file's path matches it, that file is not synced.
# If include is non-empty, and a local or remote file's path does not match it, that file is not synced.
# As a result, local files that don't pass the include/exclude filters are not uploaded to remote,
# and remote files that don't pass the include/exclude filters are not deleted.
# include = "public/*"
# exclude = "**.{jpg, png}" # would exclude files with ".jpg" or ".png" suffix
