baseURL = "https://www.michellelim.org/"
languageCode = "en-us"
title = "Michelle Lim"
theme = "ezhil"

copyright = "Copyright © 2020 Michelle Lim"

# Enable syntax highlighting.
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
googleAnalytics = "UA-123-45"

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10

# Number of characters to show in summary.
summaryLength = 20

[params]
    # Content types which are included in home page recent posts list.
    mainSections = ["post"]

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page", "post"]

    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true

    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "icons/favicon.ico"

    # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
    # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
    # you can specify custom css path as `css/custom.css`.
    customCSS = "css/custom.css"

    customJS = ["https://platform.twitter.com/widgets.js"]

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).


[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/michlimlim"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/michlimlim"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/michlimlim"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:limxlmichelle@gmail.com"


# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/writing"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Art"
url = "/art"
weight = 4
